import Navbar from "@/component/Navbar";
import "./globals.css";

export const metadata = {
  title: "User App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="container mx-auto h-[calc(100vh-0.1rem)] flex justify-center items-center">{children}</main>
      </body>
    </html>
  );
}
